package:
  name: hexrd
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  path: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  detect_binary_files_with_prefix: true
  entry_points:
    - hexrd = hexrd.cli.main:main

requirements:
  build:
    - numpy
    - python=3.9
    - setuptools
    - setuptools_scm

  run:
    - appdirs
    - fabio >=0.11
    - fast-histogram
    - h5py
    - lmfit
    - numba
    - numpy
    - psutil
    - pycifrw
    - python=3.9
    - python-xxhash
    - pyyaml
    - scikit-image
    - scikit-learn
    - scipy

test:
  imports:
    - hexrd

about:
  home: https://github.com/HEXRD/hexrd
  license: BSD
  license_family: BSD
  summary: High energy diffraction data analysis
