package:
  name: hexrd
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  path: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  detect_binary_files_with_prefix: true
  entry_points:
    - hexrd = hexrd.hedm.cli.main:main

requirements:
  build:
    # This is so that we can build cross-platform for osx-arm64
    - {{ compiler('cxx') }}
    - python {{ python }}                    # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy >=2.0                            # [build_platform != target_platform]
    # Numba is only here to make sure we use a version of numpy that is compatible
    - numba                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
  host:
    - python {{ python }}
    - numpy >=2.0
    - setuptools
    - setuptools_scm
    # Numba is only here to make sure we use a version of numpy that is compatible
    - numba
    - pybind11
    - xsimd
    - xtensor
    - xtensor-python

  run:
    - appdirs
    - chemparse
    - fabio >=0.11
    # fabio uses lxml, and lxml 4.9.1 has some crashing issue on Windows
    # so, make sure lxml >= 4.9.2 is being used
    - lxml >=4.9.2
    - h5py
    - hdf5plugin
    - lmfit
    - matplotlib-base
    - numba
    - {{ pin_compatible('numpy') }}
    - psutil
    - pycifrw
    - python
    - python-xxhash
    - pyyaml
    - scikit-image
    - scikit-learn
    - scipy
    # TBB seems to be a little faster than OpenMP for the cases I've tried.
    # Installing TBB means numba will use it instead of OpenMP.
    - tbb
    - tqdm

test:         # [build_platform == target_platform]
  imports:
    - hexrd

about:
  home: https://github.com/HEXRD/hexrd
  license: BSD
  license_family: BSD
  summary: High energy diffraction data analysis
